# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

install:
  - ./travis-tool.sh install_github hadley/testthat
  - ./travis-tool.sh install_deps

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false


after_script:
  - ./travis-tool.sh dump_logs_by_extension "timings"
  - ./travis-tool.sh dump_sysinfo
